package com.establo.service;
import com.establo.entity.*;import com.establo.exception.BusinessException;import com.establo.repository.*;import org.junit.jupiter.api.*;import java.time.*;import java.util.List;
import static org.assertj.core.api.Assertions.*;import static org.mockito.Mockito.*;
class ReportServiceTest{
 HorseRepository horses=mock(HorseRepository.class);MedicalRecordRepository medical=mock(MedicalRecordRepository.class);InventoryItemRepository inventory=mock(InventoryItemRepository.class);SupplyRecordRepository supplies=mock(SupplyRecordRepository.class);ReservationRepository reservations=mock(ReservationRepository.class);EmployeeRepository employees=mock(EmployeeRepository.class);FeedingPlanRepository plans=mock(FeedingPlanRepository.class);ReportService service=new ReportService(horses,medical,inventory,supplies,reservations,employees,plans);
 @Test void calculatesOperationalIndicators(){var today=LocalDate.now();var horse=Horse.builder().id(1L).name("Luna").code("H-01").active(true).build();var overdue=MedicalRecord.builder().horse(horse).date(today.minusDays(5)).nextDueDate(today.minusDays(1)).build();var upcoming=MedicalRecord.builder().horse(horse).date(today).nextDueDate(today.plusDays(10)).build();var item=InventoryItem.builder().id(2L).name("Heno").category("Alimento").quantity(2d).minimumStock(5d).unit("kg").build();var incoming=SupplyRecord.builder().item(item).date(today.atTime(8,0)).type("IN").quantity(1d).build();var outgoing=SupplyRecord.builder().item(item).date(today.atTime(9,0)).type("OUT").quantity(3d).build();var active=Reservation.builder().horse(horse).startAt(today.atTime(10,0)).endAt(today.atTime(11,0)).activityType("PASEO").responsible("Ana").status("SCHEDULED").participants(3).capacity(4).build();var cancelled=Reservation.builder().horse(horse).startAt(today.atTime(12,0)).endAt(today.atTime(13,0)).activityType("PASEO").responsible("Ana").status("CANCELLED").participants(2).capacity(4).build();var employee=Employee.builder().id(3L).name("Ana").role(EmployeeRole.CAREGIVER).shift(WorkShift.builder().name("06:00 - 14:00").build()).tasks(List.of(EmployeeTask.builder().title("Alimentar").status("PENDING").build(),EmployeeTask.builder().title("Limpiar").status("PENDING").build())).active(true).build();var plan=FeedingPlan.builder().horse(horse).feedType("Heno").quantity(2d).unit("kg").scheduleTime(LocalTime.of(7,0)).build();when(horses.findAll()).thenReturn(List.of(horse));when(medical.findAll()).thenReturn(List.of(overdue,upcoming));when(inventory.findAll()).thenReturn(List.of(item));when(supplies.findAll()).thenReturn(List.of(incoming,outgoing));when(reservations.findAll()).thenReturn(List.of(active,cancelled));when(employees.findAll()).thenReturn(List.of(employee));when(plans.findAll()).thenReturn(List.of(plan));var report=service.overview(today.minusDays(1),today.plusDays(1));assertThat(report.summary().overdueCare()).isEqualTo(1);assertThat(report.summary().upcomingCare()).isEqualTo(1);assertThat(report.summary().lowStockItems()).isEqualTo(1);assertThat(report.summary().feedingCoveragePercent()).isEqualTo(100);assertThat(report.inventory().getFirst().outbound()).isEqualTo(3);assertThat(report.activities().getFirst().occupancyPercent()).isEqualTo(75);assertThat(report.staff().getFirst().assignedReservations()).isEqualTo(1);assertThat(report.staff().getFirst().taskCount()).isEqualTo(2);}
 @Test void rejectsPeriodsLongerThanOneYear(){var today=LocalDate.now();assertThatThrownBy(()->service.overview(today.minusYears(2),today)).isInstanceOf(BusinessException.class).hasMessageContaining("un año");}
 @Test void filtersHealthRowsBySelectedPeriodUnlessAllHorsesAreRequested(){var today=LocalDate.now();var luna=Horse.builder().id(1L).name("Luna").code("H-01").active(true).build();var trueno=Horse.builder().id(2L).name("Trueno").code("H-02").active(true).build();var inPeriod=MedicalRecord.builder().horse(luna).date(today.minusDays(2)).build();var outsidePeriod=MedicalRecord.builder().horse(trueno).date(today.minusMonths(2)).build();when(horses.findAll()).thenReturn(List.of(luna,trueno));when(medical.findAll()).thenReturn(List.of(inPeriod,outsidePeriod));when(inventory.findAll()).thenReturn(List.of());when(supplies.findAll()).thenReturn(List.of());when(reservations.findAll()).thenReturn(List.of());when(employees.findAll()).thenReturn(List.of());when(plans.findAll()).thenReturn(List.of());var filtered=service.overview(today.minusDays(7),today);var complete=service.overview(today.minusDays(7),today,true);assertThat(filtered.health()).extracting(row->row.horse()).containsExactly("Luna");assertThat(complete.health()).extracting(row->row.horse()).containsExactly("Luna","Trueno");}
}
