CREATE TABLE work_shift (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE,
  start_time TIME,
  end_time TIME,
  active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE employee_task (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id BIGINT NOT NULL REFERENCES employee(id) ON DELETE CASCADE,
  title VARCHAR(240) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  priority VARCHAR(20) NOT NULL DEFAULT 'MEDIUM',
  due_date DATE,
  completed_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT employee_task_status_ck CHECK (status IN ('PENDING','IN_PROGRESS','COMPLETED','CANCELLED')),
  CONSTRAINT employee_task_priority_ck CHECK (priority IN ('LOW','MEDIUM','HIGH','CRITICAL'))
);

ALTER TABLE employee ADD COLUMN shift_id BIGINT;
INSERT INTO work_shift(name) SELECT DISTINCT shift FROM employee WHERE shift IS NOT NULL AND TRIM(shift) <> '';
UPDATE employee SET shift_id=(SELECT work_shift.id FROM work_shift WHERE work_shift.name=employee.shift) WHERE shift IS NOT NULL AND TRIM(shift) <> '';
ALTER TABLE employee ADD CONSTRAINT employee_shift_fk FOREIGN KEY (shift_id) REFERENCES work_shift(id);
INSERT INTO employee_task(employee_id,title) SELECT id,tasks FROM employee WHERE tasks IS NOT NULL AND TRIM(tasks) <> '';
ALTER TABLE employee DROP COLUMN shift;
ALTER TABLE employee DROP COLUMN tasks;

ALTER TABLE inventory_item ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE reservation ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

CREATE INDEX idx_employee_shift ON employee(shift_id);
CREATE INDEX idx_employee_task_employee_status ON employee_task(employee_id,status);
CREATE INDEX idx_medical_due_date ON medical_record(next_due_date);
CREATE INDEX idx_inventory_low_stock ON inventory_item(quantity,minimum_stock);
CREATE INDEX idx_notification_active_read ON notification_alert(active,is_read,created_at);
