CREATE TABLE user_audit_event (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(160) NOT NULL,
  user_role VARCHAR(40) NOT NULL,
  action VARCHAR(40) NOT NULL,
  resource VARCHAR(80) NOT NULL,
  http_method VARCHAR(10) NOT NULL,
  endpoint VARCHAR(300) NOT NULL,
  details VARCHAR(500),
  status_code INTEGER NOT NULL,
  success BOOLEAN NOT NULL,
  ip_address VARCHAR(64),
  user_agent VARCHAR(300),
  occurred_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT user_audit_event_status_ck CHECK (status_code BETWEEN 100 AND 599)
);

CREATE INDEX idx_user_audit_occurred_at ON user_audit_event(occurred_at DESC);
CREATE INDEX idx_user_audit_username_date ON user_audit_event(username,occurred_at DESC);
CREATE INDEX idx_user_audit_action_date ON user_audit_event(action,occurred_at DESC);
