package com.establo.service;
import com.establo.dto.ReportDto;import com.lowagie.text.*;import com.lowagie.text.pdf.*;import org.springframework.stereotype.Service;
import java.awt.Color;import java.io.ByteArrayOutputStream;import java.time.format.DateTimeFormatter;import java.util.List;import java.util.Locale;
@Service
public class ReportPdfService{
  private static final Color NAVY=new Color(24,43,62),BLUE=new Color(65,108,145),GOLD=new Color(190,124,73),SOFT=new Color(241,244,247),LINE=new Color(213,220,227),MUTED=new Color(96,108,121),DANGER=new Color(161,70,70);
  private static final Font TITLE=FontFactory.getFont(FontFactory.HELVETICA_BOLD,23,NAVY),SUBTITLE=FontFactory.getFont(FontFactory.HELVETICA,10,MUTED),SECTION=FontFactory.getFont(FontFactory.HELVETICA_BOLD,14,NAVY),BODY=FontFactory.getFont(FontFactory.HELVETICA,8,NAVY),BOLD=FontFactory.getFont(FontFactory.HELVETICA_BOLD,8,NAVY),WHITE=FontFactory.getFont(FontFactory.HELVETICA_BOLD,8,Color.WHITE);
  public byte[] generate(ReportDto.Overview report){try(var out=new ByteArrayOutputStream()){var document=new Document(PageSize.A4.rotate(),34,34,50,40);var writer=PdfWriter.getInstance(document,out);writer.setPageEvent(new PageBrand(report));document.addTitle("Reporte operativo - Establo Horizonte");document.addAuthor("Establo Horizonte");document.open();addCover(document,report);addHealth(document,report.health());addInventory(document,report.inventory());addActivities(document,report.activities());addStaff(document,report.staff());addFeeding(document,report.feeding());document.close();return out.toByteArray();}catch(Exception e){throw new IllegalStateException("No se pudo generar el reporte PDF",e);}}
  private void addCover(Document d,ReportDto.Overview r)throws DocumentException{var eyebrow=new Paragraph("GESTIÓN ECUESTRE  /  REPORTE OPERATIVO",FontFactory.getFont(FontFactory.HELVETICA_BOLD,8,GOLD));eyebrow.setSpacingAfter(7);d.add(eyebrow);d.add(new Paragraph("Establo Horizonte",TITLE));var period=new Paragraph("Análisis integral del "+date(r.from())+" al "+date(r.to())+"  ·  Generado "+r.generatedAt().format(DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm")),SUBTITLE);period.setSpacingBefore(4);period.setSpacingAfter(18);d.add(period);var summary=r.summary();String[][] values={{"Caballos activos",text(summary.activeHorses()),"Eventos médicos",text(summary.medicalEvents()),"Atenciones vencidas",text(summary.overdueCare())},{"Reservas",text(summary.reservations()),"Participantes",text(summary.participants()),"Stock bajo",text(summary.lowStockItems())},{"Cobertura alimentaria",percent(summary.feedingCoveragePercent()),"Atenciones próximas",text(summary.upcomingCare()),"Cancelaciones",text(summary.cancelledReservations())}};var table=new PdfPTable(new float[]{2,1,2,1,2,1});table.setWidthPercentage(100);table.setSpacingAfter(20);for(int row=0;row<values.length;row++)for(int col=0;col<values[row].length;col++){var cell=cell(values[row][col],col%2==0?BOLD:FontFactory.getFont(FontFactory.HELVETICA_BOLD,14,col%2==1&&row==0&&col==5?DANGER:BLUE),row%2==0?SOFT:Color.WHITE);cell.setPadding(col%2==0?9:8);table.addCell(cell);}d.add(table);var note=new PdfPCell(new Phrase("Este documento consolida información clínica, logística y administrativa para apoyar la toma de decisiones. Los vencimientos médicos se calculan con respecto a la fecha de generación.",SUBTITLE));note.setBackgroundColor(new Color(249,244,239));note.setBorderColor(new Color(229,205,185));note.setPadding(10);var noteTable=new PdfPTable(1);noteTable.setWidthPercentage(100);noteTable.addCell(note);noteTable.setSpacingAfter(16);d.add(noteTable);}
  private void addHealth(Document d,List<ReportDto.HealthRow> rows)throws DocumentException{section(d,"1. Salud y vencimientos","Seguimiento por caballo, registros del período y próximos controles.");String[] h={"Caballo","Código","Último registro","Eventos","Próximos","Vencidos","Próxima fecha","Estado"};List<String[]> body=rows.stream().map(x->new String[]{x.horse(),x.code(),date(x.lastRecord()),text(x.recordsInPeriod()),text(x.upcoming()),text(x.overdue()),date(x.nextDueDate()),x.risk()}).toList();d.add(table(h,body,new float[]{2.2f,1,1.35f,.8f,.9f,.8f,1.35f,1.05f}));}
  private void addInventory(Document d,List<ReportDto.InventoryRow> rows)throws DocumentException{section(d,"2. Inventario y movimientos","Disponibilidad actual, umbral mínimo y movimientos registrados en el período.");String[] h={"Insumo","Categoría","Disponible","Mínimo","Entradas","Salidas","Estado"};List<String[]> body=rows.stream().map(x->new String[]{x.item(),x.category(),number(x.stock())+" "+x.unit(),number(x.minimum())+" "+x.unit(),number(x.inbound())+" "+x.unit(),number(x.outbound())+" "+x.unit(),x.status()}).toList();d.add(table(h,body,new float[]{2.2f,1.4f,1.2f,1.2f,1.2f,1.2f,1}));}
  private void addActivities(Document d,List<ReportDto.ActivityRow> rows)throws DocumentException{section(d,"3. Reservas y ocupación","Demanda por actividad, cancelaciones y utilización de la capacidad.");String[] h={"Actividad","Reservas","Canceladas","Participantes","Capacidad","Ocupación"};List<String[]> body=rows.stream().map(x->new String[]{x.activity(),text(x.reservations()),text(x.cancelled()),text(x.participants()),text(x.capacity()),percent(x.occupancyPercent())}).toList();d.add(table(h,body,new float[]{2.2f,1,1,1.2f,1.2f,1.2f}));}
  private void addStaff(Document d,List<ReportDto.StaffRow> rows)throws DocumentException{d.newPage();section(d,"4. Carga del personal","Asignaciones de agenda, tareas declaradas, turno y estado del empleado.");String[] h={"Empleado","Rol","Turno","Reservas asignadas","Tareas","Estado"};List<String[]> body=rows.stream().map(x->new String[]{x.employee(),x.role(),safe(x.shift()),text(x.assignedReservations()),text(x.taskCount()),x.active()?"ACTIVO":"INACTIVO"}).toList();d.add(table(h,body,new float[]{2.1f,1.4f,1.8f,1.3f,1,1}));}
  private void addFeeding(Document d,List<ReportDto.FeedingRow> rows)throws DocumentException{section(d,"5. Cobertura alimentaria","Caballos cubiertos, alimentos definidos y horarios de suministro.");String[] h={"Caballo","Planes","Alimentos","Horarios","Cobertura"};List<String[]> body=rows.stream().map(x->new String[]{x.horse(),text(x.planCount()),safe(x.feedTypes()),safe(x.schedules()),x.status()}).toList();d.add(table(h,body,new float[]{2,1,2.8f,2,1.2f}));}
  private void section(Document d,String title,String description)throws DocumentException{var p=new Paragraph(title,SECTION);p.setSpacingBefore(7);p.setSpacingAfter(3);d.add(p);var sub=new Paragraph(description,SUBTITLE);sub.setSpacingAfter(7);d.add(sub);}
  private PdfPTable table(String[] headers,List<String[]> rows,float[] widths)throws DocumentException{var table=new PdfPTable(widths);table.setWidthPercentage(100);table.setHeaderRows(1);table.setSplitLate(false);for(String h:headers){var c=cell(h,WHITE,NAVY);c.setPadding(7);table.addCell(c);}if(rows.isEmpty()){var empty=cell("Sin registros para el período seleccionado",SUBTITLE,SOFT);empty.setColspan(headers.length);empty.setHorizontalAlignment(Element.ALIGN_CENTER);empty.setPadding(12);table.addCell(empty);}else{int row=0;for(String[] values:rows){for(String v:values){var c=cell(safe(v),BODY,row%2==0?Color.WHITE:SOFT);c.setPadding(6);table.addCell(c);}row++;}}table.setSpacingAfter(14);return table;}
  private PdfPCell cell(String value,Font font,Color background){var c=new PdfPCell(new Phrase(safe(value),font));c.setBackgroundColor(background);c.setBorderColor(LINE);c.setVerticalAlignment(Element.ALIGN_MIDDLE);return c;}private String date(java.time.LocalDate value){return value==null?"—":value.format(DateTimeFormatter.ofPattern("dd/MM/yyyy"));}private String percent(double value){return String.format(Locale.US,"%.1f%%",value);}private String number(double value){return String.format(Locale.US,"%.1f",value);}private String text(long value){return Long.toString(value);}private String safe(String value){return value==null||value.isBlank()?"—":value;}
  private static class PageBrand extends PdfPageEventHelper{private final ReportDto.Overview report;PageBrand(ReportDto.Overview report){this.report=report;}@Override public void onEndPage(PdfWriter writer,Document document){var canvas=writer.getDirectContent();canvas.setColorStroke(LINE);canvas.moveTo(document.left(),document.bottom()-10);canvas.lineTo(document.right(),document.bottom()-10);canvas.stroke();ColumnText.showTextAligned(canvas,Element.ALIGN_LEFT,new Phrase("EH  ·  ESTABLO HORIZONTE",FontFactory.getFont(FontFactory.HELVETICA_BOLD,7,GOLD)),document.left(),document.top()+20,0);ColumnText.showTextAligned(canvas,Element.ALIGN_RIGHT,new Phrase("Reporte "+report.from()+" — "+report.to(),FontFactory.getFont(FontFactory.HELVETICA,7,MUTED)),document.right(),document.top()+20,0);ColumnText.showTextAligned(canvas,Element.ALIGN_LEFT,new Phrase("Documento generado automáticamente",FontFactory.getFont(FontFactory.HELVETICA,7,MUTED)),document.left(),document.bottom()-24,0);ColumnText.showTextAligned(canvas,Element.ALIGN_RIGHT,new Phrase("Página "+writer.getPageNumber(),FontFactory.getFont(FontFactory.HELVETICA_BOLD,7,NAVY)),document.right(),document.bottom()-24,0);}}
}
